### ISSUE TITLE
Adding it to ats-lang/Resources

### ISSUE THREAD

**Issue by githwxi** [Hibou57/ats2-gtksourceview-language-support#1]
Thanks for the effort!

Could you add an item about this in the following file and then issue a git-pull request:

https://github.com/githwxi/ATS-Postiats/blob/master/doc/PROJECT/MEDIUM/ats2langweb/thePageRBodyRight/Resources.php
I will mention it to the students taking my CS520 class next week. I know some of them will be very happy because they use gedit :)

Cheers!

**Comment by Hibou57** [comment]
Done.

**Comment by githwxi** [comment]
I have not received the git-pull request yet.

**Comment by Hibou57** [comment]
I may have made something the wrong way (I'm not accustomed to Github).  
Did it again … please, tell me if it's OK now.

On Thu, 29 Jan 2015 21:43:53 +0100, Hongwei Xi notifications@github.com  
wrote:

> I have not received the git-pull request yet.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Yannick Duchêne

**Comment by githwxi** [comment]
Yes, it worked. See: http://www.ats-lang.org/Resources.html
