### ISSUE TITLE
String colors works bad

### ISSUE THREAD

**Issue by ghost** [Hibou57/ats2-gtksourceview-language-support#3]
Hi! Strings and chars don't have color in " and '. I use Gedit 3.18.2.

PS: Good work ;).

**Comment by Hibou57** [comment]
Please, can you paste a short line sample? Will look at it …

Thanks for the notification :)

**Comment by ghost** [comment]
![ats_code](https://cloud.githubusercontent.com/assets/11967109/12138372/b2834900-b458-11e5-8fdc-3b1c6bc1efa4.jpg)

**Comment by Hibou57** [comment]
Ok, I see. It may come as a surprise, but this is not an error. The content of the string literals and the quotes around the string literals, are not highlighted the same. The quotes are highlighted as delimiters and what's between, as literal content.

If you don't like it and can wait for some handful hours, I will tell you later what to change.

**Comment by ghost** [comment]
Oh, good. Thanks. If it is that way, I can use it without problems ^^.
